database:
    host: ${DATABASE_HOST:localhost}
    port: ${DATABASE_PORT:3360}
    name: ${DATABASE_NAME:demo}
    user: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}

bus:
    event:
        max_retries: 5
        workers: 2
    command:
        max_retries: 5
        workers: 2

management:
    endpoint:
        health:
            probes:
                enabled: true
            enabled: true
            show-details: never
            group:
                readiness:
                    include: db
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                include: health
            base-path: /
